add_header X-Frame-Options              SAMEORIGIN          always;
add_header X-Content-Type-Options       nosniff             always;
add_header Referrer-Policy              strict-origin-when-cross-origin always;
add_header Permissions-Policy           "interest-cohort=()" always;
# Allow Cloudflare Turnstile + Razorpay + Google OAuth iframes
add_header Content-Security-Policy      "frame-ancestors 'self' https://challenges.cloudflare.com https://api.razorpay.com https://accounts.google.com" always;
