server {
  listen 443 ssl;
  http2 on;
  server_name mes.dhivio.com;

  ssl_certificate     /etc/letsencrypt/live/mes.dhivio.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mes.dhivio.com/privkey.pem;
  include snippets/ssl.conf;
  include snippets/security-headers.conf;

  location / {
    proxy_pass http://mes_upstream;
    include snippets/proxy.conf;
  }
}
